# Generated by Django 3.1.5 on 2021-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danarobbins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='ticket_link',
            field=models.URLField(default='', verbose_name='Concert Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gigs',
            name='artist_name',
            field=models.CharField(default='artist', max_length=50),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='time',
            field=models.DateTimeField(default='showtime'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='venue',
            field=models.CharField(default='venue', max_length=50),
        ),
    ]
